### ISSUE TITLE
StringLiterals within StringTemplates are truncated

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.ast#92] opened 2015-08-16 02:55 UTC
There seems to be disagreement in the code as to whether ``` `` ``` and `"` should be included as text in `StringLiteral`s that are part of `StringTemplate`s, with the result being that type-checker -> AST transformations result in missing leading and trailing characters.

The code fragment ``` "abcd``1+1``efgh" ``` is used below:

### Scenario 1: Typechecker to Ceylon AST

The type checker does *not* include the extra characters:
```
|  |  |  |  |  |  |  |  |  +  [StringTemplate] (3:10-3:26) : String
|  |  |  |  |  |  |  |  |  |  + abcd [StringLiteral] (3:10-3:16) : String
|  |  |  |  |  |  |  |  |  |  + efgh [StringLiteral] (3:20-3:26) : String
|  |  |  |  |  |  |  |  |  |  +  [Expression] (3:17-3:19) : Integer
|  |  |  |  |  |  |  |  |  |  |  + + [SumOp] (3:17-3:19) : Integer
|  |  |  |  |  |  |  |  |  |  |  |  + 1 [NaturalLiteral] (3:17-3:17) : Integer
|  |  |  |  |  |  |  |  |  |  |  |  + 1 [NaturalLiteral] (3:19-3:19) : Integer
```
resulting in an incorrect Ceylon AST:
```
                                        StringTemplate {
                                            literals = [
                                                StringLiteral("""b"""),
                                                StringLiteral("""g""")
                                            ];
                                            expressions = [
                                                SumOperation {
                                                    leftSummand = IntegerLiteral("1");
                                                    rightSummand = IntegerLiteral("1");
                                                }
                                            ];
                                        }
```

### Scenario 2: AST -> Redhat -> AST
`RedHatTransformer` inserts the extra characters, resulting in a lossless roundtrip. But the interim RH step is not the same as above.
```ceylon
    value ast1 = StringTemplate {
        literals = [
            StringLiteral("abcd"),
            StringLiteral("efgh")
        ];
        expressions = [
            SumOperation {
                leftSummand = IntegerLiteral("1");
                rightSummand = IntegerLiteral("1");
            }
        ];
    };

    value rh = RedHatTransformer(SimpleTokenFactory())
                .transformStringTemplate(ast1);
    print(rh);

    value ast2 = stringTemplateToCeylon(rh);
    print(ast2);
```
result:
```
+  [StringTemplate] (0:0-0:6)
|  + "abcd`` [StringLiteral] (0:0-0:6)
|  + ``efgh" [StringLiteral] (0:0-0:6)
|  +  [Expression] (0:0-0:0)
|  |  + + [SumOp] (0:0-0:0)
|  |  |  + 1 [NaturalLiteral] (0:0-0:0)
|  |  |  + 1 [NaturalLiteral] (0:0-0:0)

StringTemplate {
    literals = [
        StringLiteral("""abcd"""),
        StringLiteral("""efgh""")
    ];
    expressions = [
        SumOperation {
            leftSummand = IntegerLiteral("1");
            rightSummand = IntegerLiteral("1");
        }
    ];
}
```
### Scenario 3: compileStringTemplate
Whatever `compileStringTemplate` does, works.
```ceylon
    value ast3 = compileStringTemplate(""""abcd``1+1``efgh"""");
    print(ast3);
```
result:
```
StringTemplate {
    literals = [
        StringLiteral("""abcd"""),
        StringLiteral("""efgh""")
    ];
    expressions = [
        SumOperation {
            leftSummand = IntegerLiteral("1");
            rightSummand = IntegerLiteral("1");
        }
    ];
}
```

**Comment by lucaswerkmeister** [comment] 2015-08-16 10:22
According to the documentation of `StringLiteral`

> ```ceylon
> "The text of the string literal (without quotes)."
> shared actual String text;
> ```

the backticks should not be included in the literal text.

It’s possible that the RedHat → `ceylon.ast` conversion assumes that all string literals have either 1 (regular) or 3 (verbatim) quotes, or something like that.

**Comment by jvasileff** [comment] 2015-08-16 21:19
The typechecker strips these chars at https://github.com/ceylon/ceylon-spec/blob/master/src/com/redhat/ceylon/compiler/typechecker/analyzer/LiteralVisitor.java#L95-L106

**Comment by lucaswerkmeister** [comment] 2015-08-16 21:25
Ah, that would be why `compileStringTemplate` works…

So in `toCeylon` we have to detect whether the quotes are still there or not, since we could be running with or without `LiteralVisitor`.

And what should `RedHatTransformer` produce? Does this need to be configurable (i. e. a class parameter)? Probably…

**Comment by lucaswerkmeister** [comment] 2015-08-20 22:01
Should be fixed now. `RedHatTransformer` got an extra parameter.

**Closed** 2015-08-20 22:00 UTC
Labels: bug

**Comment by jvasileff** [comment] 2015-08-20 22:09
Awesome, thanks!

BTW, did you notice the other fixups `LiteralVisitor.java` is doing? IIRC, there are about 4 or 5 places it mutates nodes.

**Comment by lucaswerkmeister** [comment] 2015-08-21 10:48
Yeah, looks like I’ll have to do more stuff. `LiteralVisitor`

- strips quotes
- strips leading indentation
- interprets escape sequences
  - legacy (`\n`)
  - unicode hex
  - unicode name
  - emoji
- adds `DocLink` nodes
- interprets integer and float literals

I wonder if it’s a good idea to reproduce all that in `RedHatTransformer`. We should probably be able to handle it in `toCeylon()` (check whether quotes are present etc.), but for `RedHatTransformer` it might be better to say that we always produce an AST that has to go through `LiteralVisitor`. WDYT?

**Comment by jvasileff** [comment] 2015-08-21 14:34
Is it always (and will it always be) possible to unambiguously determine if processing is required? This sounds suspicious, but I haven't looked at the details.

Is the "normal" use case of `RedHatTransformer` to feed the result into a pipeline that includes `LiteralVisitor`? I guess so, since the formatter works fine with the "raw" RedHat AST today, as I understand it.

**Comment by lucaswerkmeister** [comment] 2015-08-21 14:44
https://github.com/ceylon/ceylon-spec/blob/master/src/com/redhat/ceylon/compiler/typechecker/analyzer/LiteralVisitor.java#L47-L52

`CompilationUnit` itself apparently has a `literalsProcessed` attribute that you can check to see whether `LiteralVisitor` already passed over it.

For the individual nodes, we don’t have that, but we should be able to check something like this:
```ceylon
that.text === that.mainToken.text
```
When `LiteralVisitor` sets the text, it only sets a field of the `Node`, without updating the token. However, I’m not sure if it’s possible to trick the Ceylon compiler into comparing the identity of the underlying `java.lang.String` objects… I’ll have to test that.

I’d say the normal use case of `RedHatTransformer` is to use the resulting AST like an AST that came fresh out of `CeylonParser`. If you want to do full compilation, feed it into the full pipeline, including `LiteralVisitor`. The formatter just takes the parser’s node and doesn’t do anything else with it, so that’s why `RedHatTransformer`’s AST works there.

**Comment by jvasileff** [comment] 2015-08-21 15:05
I see. That all makes good sense to me. So I agree with your approach:

1. Autodetect for RedHat → `ceylon.ast`
2. Always produce unprocessed nodes for `ceylon.ast` → RedHat

I can't imagine a scenario where a user would actually see this ugliness:

```
|  + "abcd`` [StringLiteral] (0:0-0:6)
```

since they should be using the `ceylon.ast` visitors, etc.

**Comment by lucaswerkmeister** [comment] 2015-08-23 16:03
> We should probably be able to handle it in `toCeylon()` (check whether quotes are present etc.)

BTW, this is incorrect. Since `LiteralVisitor` also interpolates escape sequences, the String literal `"\"Hi\""` has the text `"Hi"` after going through `LiteralVisitor`, which we could interpret as `Hi`. We have to compare the literal’s and token’s `text`.

**Comment by lucaswerkmeister** [comment] 2015-08-23 20:24
Oh, and it seems we can’t compare the *identity* of the texts, since `CommonToken` doesn’t always store its text either, but instead seems to reinstantiate it from the underlying input. Equality test will have to do.

**Comment by lucaswerkmeister** [comment] 2015-08-26 20:39
Question: If we detect the literal was visited by `LiteralVisitor`… which text should we put in the `ceylon.ast` node? The original text from the token, or the text from the node (with interpreted escape sequences, exponents, etc)? I’m leaning towards the former, but perhaps the latter is more useful? WDYT @jvasileff?

**Comment by jvasileff** [comment] 2015-08-26 22:03
I think it's important to always present `ceylon.ast` nodes with the same amount of processing, regardless of their history. I think it's ugly (but understandable) that the type checker leaks an intermediate form of its tree.

My preference would be to have the post-`LiteralVisitor` form be the standard, but is that consistent with other `ceylon.ast` goals? Can processing always be reversed to faithfully reproduce the original content, if that's important? Surely it can be done for the original string template issue, but I haven't really looked at the other conversions.

**Comment by lucaswerkmeister** [comment] 2015-08-26 22:06
> My preference would be to have the post-`LiteralVisitor` form be the standard

Impossible, pure Ceylon doesn’t give me the information to decode `"\{ELEPHANT}"`. The character names aren’t available in JS.

> Can processing always be reversed to faithfully reproduce the original content, if that's important?

I don’t think so, how would you distinguish between `"a"` and `"\{LATIN SMALL LETTER A}"`?

**Comment by jvasileff** [comment] 2015-08-26 22:55
Ok, yeah, I guess I'd go with the raw form except when when processing is obviously better (and reversible, if important). Consumers of `ceylon.ast` shouldn't write code that is dependent on a particular processing pipeline that can't be enforced by the type system. And the `update` feature allows explicit use of type checker output.

**Comment by luolong** [comment] 2015-08-27 21:58
I just recently heard a podcast where someone was explaining how new Roslyn compiler ast used some extra data on nodes (I think they called those _Trivia_) for inserting and retaining information like comments and formatting related details about an AST node...

**Comment by gavinking** [comment] 2015-08-29 06:19
@luolong I dunno, I don't really see how that could be non-fragile, since it's unclear which node a comment "belongs" to. Comments aren't annotations.

**Comment by luolong** [comment] 2015-08-30 18:11
Its by convention. 

we all know that line comments usually go before the block of text they are meant to "decorate"

Same would work for white space before and after some code. And if the distinction between triple quotes and plain quotes will be erased in AST, the "Trivia" node seems to be just the right type _trivia_ to be attached to the string literal AST node.

**Comment by gavinking** [comment] 2015-08-30 23:03
The point is this is ambiguous. Which node do they decorate? The expression? The statement? The nested expression?
